name: Libraries CI/CD

on:
  push:
    branches: [ "main", "dev"]

jobs:
  installing_running_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installing pnpm packages
        run: pnpm install

      - name: Running Eslint
        run: pnpm run lint

      - name: Running Test
        run: pnpm run test:cov

  create_admin_user:
    runs-on: ubuntu-latest
    needs: installing_running_test
    
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installing pnpm packages
        run: pnpm install

      - name: Run API to Create Tables
        env:
          PORT: ${{ secrets.PORT }}
          DB_URL: ${{ secrets.DB_URL }}
        run: pnpm run start:dev

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: inserting admin user into database
        run: psql ${{ secrets.DB_URL }} -a -f ../../init.sql

  docker:
    runs-on: ubuntu-latest
    needs: create_admin_user

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
